### ISSUE TITLE
Script dies if locale is not available on the system

### ISSUE THREAD

**Issue by jomue** [flrs/poemGenerator#2]
The script tries to set the locale to de_DE.UTF-8 in the beginning, which fails on systems without that locale.

One possible solution would be to handle the exception by printing a warning and then proceeding with the script execution.
```
try:
    locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
except locale.Error:
    print "Cannot set locale to de_DE.UTF-8"
```

I'm not sure if it has any side effects, but it appears to work on my system.

**Comment by flrs** [comment]
Implemented suggested fix in commit https://github.com/flrs/poemGenerator/commit/d2b1f74718f87402d35d70043ead03ffad2babde
